Tässä Notebookissaa käydään läpi muutamia periaatteita ja funktioita, joita tarvitset sekä DFT:n että signaalin spektrin muodostamisessa.
Osa hyödyllisistä funktioista on käyty läpi Octaven perustoimintojen tai kompleksilukujen yhteydessä, eikä niitä enää käsitellä tässä Notebookissa perusteellisesti. 

DFT:n muodostaminen fft-funktiolla ja reaali-/imaginaariosin käsittely

In [13]:
x=[1,5 -3, 7, 0, 1 -8]; % luodaan signaali
x_DFT=fft(x) %muodostetaan DFT
x_DFT_real=real(x_DFT) %irrotetaan reaaliosat
x_DFT_imag=imag(x_DFT) %irrotetaan imaginaariosat

x_DFT =

 Columns 1 through 3:

    3.00000 +  0.00000i   -6.73221 -  9.30128i    7.83393 -  8.93678i

 Columns 4 through 6:

    0.89828 - 15.59231i    0.89828 + 15.59231i    7.83393 +  8.93678i

 Column 7:

   -6.73221 +  9.30128i

x_DFT_real =

   3.00000  -6.73221   7.83393   0.89828   0.89828   7.83393  -6.73221

x_DFT_imag =

    0.00000   -9.30128   -8.93678  -15.59231   15.59231    8.93678    9.30128



Taulukon muodostaminen ja alkioiden summaaminen (Toimii myös kompleksiluvuille)

In [14]:
rivit=3; %rivien määrä
sarakkeet=3; %sarakkeiden määrä
taulu=zeros(rivit,sarakkeet); %Luodaan nollataulukko

for r = 1:rivit
    for s = 1:sarakkeet

    taulu(r,s)=r*s; %Muodostetaan taulukko kertomalla keskenään rivin ja sarakkeen indeksi
    end
end

disp(taulu)

rivisumma=sum(taulu,2) %sumataa rivien alkiot keskenään
sarakesumma=sum(taulu,1) %Summataan sarakkeiden alkiot keskenään
    

   1   2   3
   2   4   6
   3   6   9
rivisumma =

    6
   12
   18

sarakesumma =

    6   12   18



Alkioiden summaaminen silmukassa

In [15]:
rivit=3; %rivien määrä
sarakkeet=3; %sarakkeiden määrä
summa=zeros(rivit,1); %Luodaan nollataulukko

for r = 1:rivit
    for s = 1:sarakkeet
    summa(r,1)=summa(r,1)+r*s; %summataan alkiot keskenään kumulatiivisesti. Summaukseen otetaan mukaan edellinen arvo.
    end
end

disp(summa)

    6
   12
   18
